scrum_template/app/rooms/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, BooleanField, SubmitField 
from wtforms import TextAreaField, FileField, DecimalField, IntegerField, SelectField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length, NumberRange

class AddRoomForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(),Length(min=4, max=30)])
    description = TextAreaField('Description', validators=[DataRequired(), Length(min=50, max=5000)])
    image = FileField('Add image', validators=[FileAllowed(['jpg', 'png'])])
    price = DecimalField('Price', validators=[DataRequired()])
    submit = SubmitField('Add room')

class EditRoomForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(),Length(min=4, max=100)])
    description = TextAreaField('Description', validators=[DataRequired(), Length(min=50, max=5000)])
    image = FileField(
        'Update room image - <span style="color:red;">only replace if old or incorrect</span>', 
        validators=[
            FileAllowed(['jpg', 'png'], 'Images only with extension .jpg or .png')
        ]
    )
    price = DecimalField('Price', validators=[DataRequired()])
    update = SubmitField('Update')
    cancel = SubmitField('Cancel')

scrum_template/app/rooms/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from app.rooms.forms import AddRoomForm, EditRoomForm
from app.models import Room
from app.funcs import save_picture
from app import db
from flask_login import current_user, login_user, logout_user, login_required

rooms = Blueprint('rooms', __name__)

@rooms.route('/all_rooms')
def all_rooms():
    return 'All rooms page'

@rooms.route('/new_room', methods=['GET', 'POST'])
@login_required
def new_room():
    form = AddRoomForm()
    if form.validate_on_submit():
        image_file = 'default.jpg'
        if form.image.data:
            image_file = save_picture(form.image.data)
  
        room = Room(
            title=form.title.data,
            description=form.description.data,
            image=image_file,
            price=form.price.data,
        )
        db.session.add(room)
        db.session.flush()
        new_id = room.id
        db.session.commit()
        flash('Room was added successfully', 'success')
        return redirect(url_for('rooms.room', id=new_id))
    return render_template('rooms/new_room.html', title='Add room', form=form)

@rooms.route('/room/<id>', methods=['GET', 'POST'])
def room(id):
    room = Room.query.get(id)
    return render_template('rooms/room.html', title=room.title.title(), room=room)

@rooms.route('/room/edit/<id>', methods=['GET', 'POST'])
@login_required
def edit_room(id):
    room = Room.query.get(id)
    form = EditRoomForm(obj=room)
    if request.method == 'GET':
        form.populate_obj(room)
    elif request.method == 'POST':
        if form.update.data and form.validate_on_submit():
            room.title = form.title.data
            room.description = form.description.data
            if form.image.data:
                room.image = save_picture(form.image.data)
            room.price = form.price.data
            db.session.commit()
            flash ('Update was successful', 'success')
            return redirect(url_for('rooms.room', id=id))
        if form.cancel.data:
            return redirect(url_for('rooms.room', id=id))
    return render_template('rooms/edit_room.html', title='Edit room', form=form)

@rooms.route('/room/<id>/delete', methods=['GET', 'POST'])
@login_required
def delete_room(id):
    if Room.query.filter_by(id=id).delete():
        db.session.commit()
        flash ('Room has been deleted', 'success')
        return redirect(url_for('main.index'))
    return redirect(url_for('rooms.room', id=id)) 

@rooms.route('/search', methods=['GET', 'POST'])
def search():
    rooms = None
    target_string = request.form['search']

    rooms = Room.query.filter(Room.title.contains(target_string)).all()

    if target_string == '':
        search_msg = f'No matching records found - displaying all {len(rooms)} rooms'
        color = 'danger'
    else:
        search_msg = f'{len(rooms)} rooms found'
        color = 'success'
    return render_template('rooms/search.html', 
        title='Search result', rooms=rooms, 
        search_msg=search_msg, color=color
    )

scrum_template/app/templates/rooms/_rooms.html
{% for room in rooms %}
<div class="col-sm-6 col-md-3">
    <a href="{{ url_for('rooms.room', id=room.id) }}" class="thumbnail" data-toggle="tooltip" data-placement="top" title="Select image for more details">
        <img src="{{ url_for('static', filename='room_pics/' + room.image) }}" alt="" class="img-responsive">
        <!-- <div class="caption text-muted">
            <p><b>{{book.title.title()}}</b></p>
        </div> -->
    </a>
</div>
{% endfor %}

scrum_template/app/templates/rooms/edit_room.html
{% extends "base.html" %} {% import 'bootstrap/wtf.html' as wtf %} {% block app_content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Edit room</h3>
            </div>
            <div class="panel-body">
                {{ wtf.quick_form(form, button_map={'update':'success', 'cancel' : 'default'}, extra_classes="text-muted") }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

scrum_template/app/templates/rooms/new_room.html
{% extends "base.html" %} {% import 'bootstrap/wtf.html' as wtf %} {% block app_content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Add a new room</h3>
            </div>
            <div class="panel-body">
                {{ wtf.quick_form(form, button_map={'submit':'success'}, extra_classes="text-muted") }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

scrum_template/app/templates/rooms/room.html
{% extends "base.html" %} {% import 'bootstrap/wtf.html' as wtf %} {% block app_content %}
<div class="container">
    <div class="col-sm-6 col-md-3">
        <div class="row">
            <img src="{{ url_for('static', filename='room_pics/' + room.image) }}" alt="" class="thumbnail"> {% if current_user.is_authenticated and current_user.admin %}
            <a href="{{ url_for('rooms.edit_room', id=room.id) }}" class="btn btn-primary">Edit</a>
            <!-- Button trigger modal -->
            <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#deleteroom">Delete</a> {% endif %}
            <a href="{{ url_for('main.index') }}" class="btn btn-default">Return to all rooms</a>
        </div>
    </div>

    <!-- Delete room Modal-->
    <div class="modal fade" id="deleteroom" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title" id="deleteModalLabel">Deleting room: {{ room.title }}</h3>
                </div>
                <div class="modal-body">
                    <h4>Are you sure?</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <a href="{{ url_for('rooms.delete_room', id=room.id) }}" class="btn btn-danger">Yes</a>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <div class="content-section">
            <h3>{{ room.title.title() }}</h3>
            <h5><b>£{{room.price}}</b></h5>

            <hr>
            <h4>Description</h4>
            <p class="text-justify">{{ room.description }}</p>
            <hr>
        </div>
    </div>
    <br><br>
    <hr>
</div><br> {% endblock %}

scrum_template/app/templates/rooms/search.html
{% extends "base.html" %}

{% block app_content %} 
<div class="container">
    <div class="col-md-9 col-md-offset-1">
        <div class = "row ">
    
            <h3 class='text-muted' style="padding-left:20px;">Search result: <span class="text-{{color}}">{{ search_msg }}</span></h3><hr>
            {% include 'rooms/_rooms.html' %}
        </div>
    </div>
</div>
{% endblock %}