scrum_template/app/reviews/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TimeField
from wtforms import TextAreaField, FileField, DecimalField, IntegerField, SelectField
from wtforms.fields.html5 import DateField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length, NumberRange

class ReviewForm(FlaskForm):
    rating = DecimalField(default=0.0, validators=[NumberRange(min=0, max=5)])
    text = TextAreaField('Write a review!')
    submit = SubmitField('Submit')

scrum_template/app/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from app.models import Enquiry, Review
from app.enquiries.forms import ContactForm
from app.reviews.forms import ReviewForm
from sqlalchemy.sql import func
from app import db
from flask_login import current_user, login_user, logout_user, login_required

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/index', methods=['GET', 'POST'])
def index():
    return render_template('index.html',  title='Home')
    
@main.route('/contact', methods=['GET', 'POST'])
def contact():
    # link the form
    form = ContactForm()
    # if form is submitted
    if form.validate_on_submit():
        # store the parameters from the form
        enquiry = Enquiry(
            first_name = form.first_name.data,
            last_name = form.last_name.data,
            email = form.email.data,
            telno = form.telno.data,
            description = form.description.data
        )
        # push it to the database
        db.session.add(enquiry)
        db.session.flush()
        db.session.commit()
        # display a message
        flash('Thank you, we will be in touch with you soon!', 'success')
        return redirect(url_for('main.contact'))
    return render_template('contact.html', title = 'Contact', form=form)

@main.route('/enquiries', methods=['GET', 'POST'])
@login_required
def enquiries():
    enquiries = None
    # fetch all equiries from the database
    enquiries = Enquiry.query.all()
    # record counter
    msg = f'{len(enquiries)} Enquiry(ies)'
    color = 'success'
    return render_template('enquiries.html', title='All enquiries', enquiries=enquiries, msg=msg, color=color)

@main.route('/packagedeals',methods=['GET','POST'])
def packagedeals():
    return render_template('packagedeals.html', title = 'Package Deals')

@main.route('/services', methods=['GET','POST'])
def services():
    return render_template('services.html', title = 'Services')

@main.route('/reviews', methods=['GET','POST'])
def reviews():
    reviews = None
    # running a query to get all reviews
    reviews = Review.query.all()
    # link the form
    form = ReviewForm()
    # count the average of all review ratings
    temp = db.session.query(func.avg(Review.rating).label('average'))
    # if average exists
    if temp[0].average:
        # round up the average to two decimal places
        avg = round(temp[0].average, 2) 
    else: 
        avg = 0

    if form.validate_on_submit():
        # fetch the count of current user's review (supposed to be either none or one)
        rev = Review.query.filter_by(user_id=current_user.get_id()).count()
        #if it's not 0 i.e. there's a review already written by the user
        if rev != 0:
            # display message
            flash("Can't review a book twice. Please edit/update your previous review", "warning")
        # if user hasn't written a review before, accept the parameters from the form
        else:
            review = Review(
                rating = round(form.rating.data, 2),
                text = form.text.data,
                user_id = current_user.get_id()
            )
            flash("Review has been added", "success")
            # push the review to the database
            db.session.add(review)
            db.session.commit()
        return redirect(url_for('main.reviews'))
    return render_template('reviews/reviews.html', title = 'Reviews', reviews=reviews, form=form, average=avg)

@main.route('/edit_review', methods=['GET', 'POST'])
@login_required
def edit_review():
    # fetch the current user's review
    review = Review.query.filter_by(user_id=current_user.get_id())[0]
    # link the form
    form = ReviewForm()
    # if get - display the review text in the form's text box
    if request.method == 'GET':
        form.text.data = review.text 
    # if form is submitted and post'ed - fetch the new rating/text and push it to the database
    if form.validate_on_submit() and request.method == 'POST':
        review.rating = round(form.rating.data, 2)
        review.text = form.text.data
        db.session.commit()
        return redirect(url_for('main.reviews'))
    return render_template('reviews/edit_review.html', title="Edit review", form=form)

@main.route('/delete_review/<id>', methods=['GET', 'POST'])
@login_required
def delete_review(id):
    # get the id of the review and delete it
    if Review.query.filter_by(id=id).delete():
        db.session.commit()
        flash ('Review has been deleted', 'success')
        return redirect(url_for('main.reviews'))
    return redirect(url_for('main.reviews'))  

scrum_template/app/templates/reviews/_review_form.html
<div id="star"></div>
<form method="POST" action="">
    {{ form.hidden_tag() }} {{ wtf.form_field(form.rating, id ='result', type="hidden") }} {{ wtf.form_field(form.text, rows="4") }} {{ wtf.form_field(form.submit, button_map={'submit':'success'}) }}
</form>

scrum_template/app/templates/reviews/_reviews.html
<div>
    {% if average %}
    <b>Average rating: <span class="avg-rating" data-score="{{ average }}" > </span> ({{ average }})</b> {% endif %}
</div><br> {% for review in reviews %}
<div class="panel panel-default">
    <div class="panel-heading">
        <span class="glyphicon glyphicon-user" aria-hidden="true" style="padding-right:5px;"></span>
        <span>{{ review.user.first_name.upper() }}</span><br>
        <span class="star-rating" data-score="{{ review.rating }}"></span><br>
        <span class="text-right">Created {{ moment(review.created_at).fromNow() }}</span> {% if review.updated %}
        <br><span class="text-right">Updated {{ moment(review.updated_at).fromNow() }}</span> {% endif %}
    </div>
    <div class="panel-body">
        <p class="text-justify">{{ review.text }}</p>
        <hr> {% if current_user.username == review.user.username %}
        <a href="{{ url_for('main.edit_review') }}" class="btn btn-primary btn-sm">Edit </a>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal">
                    Delete
                </button>
        <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title" id="deleteModalLabel">Deleting review</h3>
                    </div>
                    <div class="modal-body">
                        <h4>Are you sure?</h4>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                        <a href="{{ url_for('main.delete_review', id=review.id) }}" class="btn btn-success">Yes</a>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endfor %}

scrum_template/app/templates/reviews/edit_review.html
{% extends "base.html" %} {% import 'bootstrap/wtf.html' as wtf %} {% block app_content %}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h3>Edit review</h3>
        {% if current_user.is_authenticated %} {% include 'reviews/_review_form.html' %}
        <br>
        <a href="{{ url_for('main.reviews') }}" class="btn btn-default">Cancel</a> {% endif %}
    </div>
</div>

{% endblock %}

scrum_template/app/templates/reviews/reviews.html
{% extends "base.html" %} {% import 'bootstrap/wtf.html' as wtf %} {% block app_content %}
<div class="container">
    <div class="col-md-9 col-md-offset-1">
        <div class="row ">
            <h3 class="text-muted">Reviews</h3>
            {% if current_user.is_authenticated and not current_user.admin %} {% include 'reviews/_review_form.html' %} {% endif %} {% include 'reviews/_reviews.html' %}
        </div>
    </div>
</div>
{% endblock %}