scrum_template/app/bookings/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TimeField
from wtforms import TextAreaField, FileField, DecimalField, IntegerField, SelectField
from wtforms.fields.html5 import DateField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length, NumberRange

class AddWeddingBookingForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    telno = StringField('Telephone Number',validators=[DataRequired()])
    date = DateField('Date', format='%Y-%m-%d', validators=[DataRequired()])
    incl_catering = BooleanField('Catering')
    incl_flowers = BooleanField('Flowers')
    incl_carhire = BooleanField('Car Hire')
    incl_visual_and_audio = BooleanField('Visual & Audio System')
    incl_photography = BooleanField('Photography')
    submit = SubmitField('Submit')

class EditWeddingBookingForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    telno = StringField('Telephone Number',validators=[DataRequired()])
    date = DateField('Date', format='%Y-%m-%d', validators=[DataRequired()])
    incl_catering = BooleanField('Catering')
    incl_flowers = BooleanField('Flowers')
    incl_carhire = BooleanField('Car Hire')
    incl_visual_and_audio = BooleanField('Visual & Audio System')
    incl_photography = BooleanField('Photography')
    update = SubmitField('Update')
    cancel = SubmitField('Cancel')
    delete = SubmitField('Delete')

class AddTourBookingForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    telno = StringField('Telephone Number',validators=[DataRequired()])
    date = DateField('Date', format='%Y-%m-%d', validators=[DataRequired()])
    time_id = SelectField('Time', coerce=int)
    submit = SubmitField('Submit')

class EditTourBookingForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    telno = StringField('Telephone Number',validators=[DataRequired()])
    date = DateField('Date', format='%Y-%m-%d', validators=[DataRequired()])
    time_id = SelectField('Time', coerce=int)
    update = SubmitField('Update')
    cancel = SubmitField('Cancel')
    delete = SubmitField('Delete')

scrum_template/app/bookings/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from app.models import WedBooking, TourBooking, Time
from app.bookings.forms import AddWeddingBookingForm, AddTourBookingForm, EditWeddingBookingForm, EditTourBookingForm
from app import db
from flask_login import current_user, login_user, logout_user, login_required

bookings = Blueprint('bookings', __name__)

@bookings.route('/wedbooking', methods=['GET', 'POST'])
@login_required
def wedbooking():
    # link the form
    form = AddWeddingBookingForm()
    # if form is submitted, gather the parameters from the form and store it into wedbookings
    if form.validate_on_submit():
        wedbooking = WedBooking(
            first_name = form.first_name.data,
            last_name = form.last_name.data,
            email = form.email.data,
            telno = form.telno.data,
            date = form.date.data,
            incl_catering = form.incl_catering.data,
            incl_flowers = form.incl_flowers.data,
            incl_carhire = form.incl_carhire.data,
            incl_visual_and_audio = form.incl_visual_and_audio.data,
            incl_photography = form.incl_photography.data
        )
        # push the new wedbooking to the database
        db.session.add(wedbooking)
        db.session.flush()
        db.session.commit()
        # display a message
        flash('Thank you, we will be in touch with you soon!', 'success')
        return redirect(url_for('bookings.wedbooking'))
    return render_template('bookings/new_wedding.html', title = 'Wedding Booking', form=form)

@bookings.route('/wedbookings', methods=['GET', 'POST'])
@login_required
def wedbookings():
    wedbookings = None
    # run a query for all wedbookings
    wedbookings = WedBooking.query.all()
    # record counter
    msg = f'{len(wedbookings)} Wedding Booking(s)'
    color = 'success'
    return render_template('bookings/wedbookings.html', title='All Wedding Bookings', wedbookings=wedbookings, msg=msg, color=color)

@bookings.route('/wedbooking/edit/<id>', methods=['GET', 'POST'])
@login_required
def edit_wedbooking(id):
    wedbooking = WedBooking.query.get(id)
    form = EditWeddingBookingForm(obj=wedbooking)
    if request.method == 'GET':
        form.populate_obj(wedbooking)
    elif request.method == 'POST':
        if form.update.data and form.validate_on_submit():
            wedbooking.first_name = form.first_name.data
            wedbooking.last_name = form.last_name.data
            wedbooking.email = form.email.data
            wedbooking.telno = form.telno.data
            wedbooking.date = form.date.data
            wedbooking.incl_catering = form.incl_catering.data
            wedbooking.incl_visual_and_audio = form.incl_visual_and_audio.data
            wedbooking.incl_photography = form.incl_photography.data
            wedbooking.incl_flowers = form.incl_flowers.data
            wedbooking.incl_carhire = form.incl_carhire.data
            db.session.commit()
            flash ('Update was successful', 'success')
            return redirect(url_for('bookings.wedbookings'))
        if form.cancel.data:
            return redirect(url_for('bookings.wedbookings'))
        if form.delete.data:
            if wedbooking.query.filter_by(id=id).delete():
                db.session.commit()
                flash ('Wedding Booking has been deleted', 'success')
                return redirect(url_for('bookings.wedbookings'))
    return render_template('bookings/edit_wedbooking.html', title='Edit Tour Booking', form=form)

@bookings.route('/tourbooking', methods=['GET', 'POST'])
@login_required
def tourbooking():
    # link the form
    form = AddTourBookingForm()
    # populate the select field with time hours
    form.time_id.choices = [(time.id, time.hour.title()) for time in Time.query.all()]
    # if form is submitted store the parameters
    if form.validate_on_submit():
        tourbooking = TourBooking(
            first_name = form.first_name.data,
            last_name = form.last_name.data,
            email = form.email.data,
            telno = form.telno.data,
            date = form.date.data,
            time_id = form.time_id.data
        )
        # push the new tourbooking to the database
        db.session.add(tourbooking)
        db.session.flush()
        db.session.commit()
        # display a message
        flash('Thank you, we will be in touch with you soon!', 'success')
        return redirect(url_for('bookings.tourbooking'))
    return render_template('bookings/new_tour.html', title = 'Tour Booking', form=form)

@bookings.route('/tourbookings', methods=['GET', 'POST'])
@login_required
def tourbookings():
    tourbookings = None
    # run a query for all tour bookings
    tourbookings = TourBooking.query.all()
    # record counter
    msg = f'{len(tourbookings)} Tour Booking(s)'
    color = 'success'
    return render_template('bookings/tourbookings.html', title='All Tour Bookings', tourbookings=tourbookings, msg=msg, color=color)

@bookings.route('/tourbooking/edit/<id>', methods=['GET', 'POST'])
@login_required
def edit_tourbooking(id):
    tourbooking = TourBooking.query.get(id)
    form = EditTourBookingForm(obj=tourbooking)
    form.time_id.choices = [(time.id, time.hour.title()) for time in Time.query.all()]
    if request.method == 'GET':
        form.populate_obj(tourbooking)
    elif request.method == 'POST':
        if form.update.data and form.validate_on_submit():
            tourbooking.first_name = form.first_name.data
            tourbooking.last_name = form.last_name.data
            tourbooking.email = form.email.data
            tourbooking.telno = form.telno.data
            tourbooking.date = form.date.data
            tourbooking.time_id = form.time_id.data
            db.session.commit()
            flash ('Update was successful', 'success')
            return redirect(url_for('bookings.tourbookings'))
        if form.cancel.data:
            return redirect(url_for('bookings.tourbookings'))
        if form.delete.data:
            if tourbooking.query.filter_by(id=id).delete():
                db.session.commit()
                flash ('Tour Booking has been deleted', 'success')
                return redirect(url_for('bookings.tourbookings'))
    return render_template('bookings/edit_tourbooking.html', title='Edit Tour Booking', form=form)

scrum_template/app/templates/bookings/_tourbookings.html
<table class="table">
    <tbody>
        <tr>
            <th>Submission Date</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Telephone Number</th>
            <th>Date</th>
            <th>Time</th>
            <th></th>
        </tr>
        {% for tourbooking in tourbookings %}
        <tr>
            <td>{{ tourbooking.created_at }}</td>
            <td>{{ tourbooking.first_name }}</td>
            <td>{{ tourbooking.last_name }}</td>
            <td>{{ tourbooking.email }}</td>
            <td>{{ tourbooking.telno }}</td>
            <td>{{ tourbooking.date }}</td>
            <td>{{ tourbooking.time.hour }}</td>
            <td><a href="{{ url_for('bookings.edit_tourbooking', id=tourbooking.id) }}" class="btn btn-primary btn-sm">Edit</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

scrum_template/app/templates/bookings/_wedbookings.html
<table class="table">
    <tbody>
        <tr>
            <th>Submission Date</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Telephone Number</th>
            <th>Date</th>
            <th>Catering</th>
            <th>Flower Decor</th>
            <th>Car Hire</th>
            <th>Visual & Audio</th>
            <th>Photography</th>
            <th></th>
        </tr>
        {% for wedbooking in wedbookings %}
        <tr>
            <td>{{ wedbooking.created_at }}</td>
            <td>{{ wedbooking.first_name }}</td>
            <td>{{ wedbooking.last_name }}</td>
            <td>{{ wedbooking.email }}</td>
            <td>{{ wedbooking.telno }}</td>
            <td>{{ wedbooking.date }}</td>
            <td>{{ wedbooking.incl_catering }}</td>
            <td>{{ wedbooking.incl_flowers }}</td>
            <td>{{ wedbooking.incl_carhire }}</td>
            <td>{{ wedbooking.incl_visual_and_audio }}</td>
            <td>{{ wedbooking.incl_photography }}</td>
            <td><a href="{{ url_for('bookings.edit_wedbooking', id=wedbooking.id) }}" class="btn btn-primary btn-sm">Edit</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

scrum_template/app/templates/bookings/edit_tourbooking.html
{% extends "base.html" %} {% import 'bootstrap/wtf.html' as wtf %} {% block app_content %}
<br><br>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Edit Tour Booking</h3>
            </div>
            <div class="panel-body">
                {{ wtf.quick_form(form, button_map={'update':'success', 'delete' : 'danger', 'cancel' : 'default'}, extra_classes="text-muted") }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

scrum_template/app/templates/bookings/edit_wedbooking.html
{% extends "base.html" %} {% import 'bootstrap/wtf.html' as wtf %} {% block app_content %}
<br><br>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Edit Wedding Booking</h3>
            </div>
            <div class="panel-body">
                {{ wtf.quick_form(form, button_map={'update':'success', 'delete' : 'danger', 'cancel' : 'default'}, extra_classes="text-muted") }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

scrum_template/app/templates/bookings/new_tour.html
{% extends "base.html" %} {% import 'bootstrap/wtf.html' as wtf %} {% block app_content %}
<br><br>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Create a Tour Booking</h3>
            </div>
            <div class="panel-body">
                {{ wtf.quick_form(form, button_map={'submit':'success'}, extra_classes="text-muted") }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

scrum_template/app/templates/bookings/new_wedding.html
{% extends "base.html" %} {% import 'bootstrap/wtf.html' as wtf %} {% block app_content %}
<br><br>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Create a Wedding Booking</h3>
            </div>
            <div class="panel-body">
                {{ wtf.quick_form(form, button_map={'submit':'success'}, extra_classes="text-muted") }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

scrum_template/app/templates/bookings/tourbookings.html
{% extends "base.html" %} {% block app_content %}
<div class="container">
    <div class="col-md-9 col-md-offset-1">
        <div class="row ">
            <h3 class="text-muted">Displaying <span class="text-{{color}}">{{ msg }}</span></h3>
            <hr> {% include 'bookings/_tourbookings.html' %}
        </div>
    </div>
</div>
{% endblock %}

scrum_template/app/templates/bookings/wedbookings.html
{% extends "base.html" %} {% block app_content %}
<div class="container">
    <div class="col-md-9 col-md-offset-1">
        <div class="row ">
            <h3 class="text-muted">Displaying <span class="text-{{color}}">{{ msg }}</span></h3>
            <hr> {% include 'bookings/_wedbookings.html' %}
        </div>
    </div>
</div>
{% endblock %}