scrum_template/app/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from app.models import Enquiry, Review
from app.enquiries.forms import ContactForm
from app.reviews.forms import ReviewForm
from sqlalchemy.sql import func
from app import db
from flask_login import current_user, login_user, logout_user, login_required

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/index', methods=['GET', 'POST'])
def index():
    return render_template('index.html',  title='Home')
    
@main.route('/contact', methods=['GET', 'POST'])
def contact():
    # link the form
    form = ContactForm()
    # if form is submitted
    if form.validate_on_submit():
        # store the parameters from the form
        enquiry = Enquiry(
            first_name = form.first_name.data,
            last_name = form.last_name.data,
            email = form.email.data,
            telno = form.telno.data,
            description = form.description.data
        )
        # push it to the database
        db.session.add(enquiry)
        db.session.flush()
        db.session.commit()
        # display a message
        flash('Thank you, we will be in touch with you soon!', 'success')
        return redirect(url_for('main.contact'))
    return render_template('contact.html', title = 'Contact', form=form)

@main.route('/enquiries', methods=['GET', 'POST'])
@login_required
def enquiries():
    enquiries = None
    # fetch all equiries from the database
    enquiries = Enquiry.query.all()
    # record counter
    msg = f'{len(enquiries)} Enquiry(ies)'
    color = 'success'
    return render_template('enquiries.html', title='All enquiries', enquiries=enquiries, msg=msg, color=color)

@main.route('/packagedeals',methods=['GET','POST'])
def packagedeals():
    return render_template('packagedeals.html', title = 'Package Deals')

@main.route('/services', methods=['GET','POST'])
def services():
    return render_template('services.html', title = 'Services')

@main.route('/reviews', methods=['GET','POST'])
def reviews():
    reviews = None
    # running a query to get all reviews
    reviews = Review.query.all()
    # link the form
    form = ReviewForm()
    # count the average of all review ratings
    temp = db.session.query(func.avg(Review.rating).label('average'))
    # if average exists
    if temp[0].average:
        # round up the average to two decimal places
        avg = round(temp[0].average, 2) 
    else: 
        avg = 0

    if form.validate_on_submit():
        # fetch the count of current user's review (supposed to be either none or one)
        rev = Review.query.filter_by(user_id=current_user.get_id()).count()
        #if it's not 0 i.e. there's a review already written by the user
        if rev != 0:
            # display message
            flash("Can't review a book twice. Please edit/update your previous review", "warning")
        # if user hasn't written a review before, accept the parameters from the form
        else:
            review = Review(
                rating = round(form.rating.data, 2),
                text = form.text.data,
                user_id = current_user.get_id()
            )
            flash("Review has been added", "success")
            # push the review to the database
            db.session.add(review)
            db.session.commit()
        return redirect(url_for('main.reviews'))
    return render_template('reviews/reviews.html', title = 'Reviews', reviews=reviews, form=form, average=avg)

@main.route('/edit_review', methods=['GET', 'POST'])
@login_required
def edit_review():
    # fetch the current user's review
    review = Review.query.filter_by(user_id=current_user.get_id())[0]
    # link the form
    form = ReviewForm()
    # if get - display the review text in the form's text box
    if request.method == 'GET':
        form.text.data = review.text 
    # if form is submitted and post'ed - fetch the new rating/text and push it to the database
    if form.validate_on_submit() and request.method == 'POST':
        review.rating = round(form.rating.data, 2)
        review.text = form.text.data
        db.session.commit()
        return redirect(url_for('main.reviews'))
    return render_template('reviews/edit_review.html', title="Edit review", form=form)

@main.route('/delete_review/<id>', methods=['GET', 'POST'])
@login_required
def delete_review(id):
    # get the id of the review and delete it
    if Review.query.filter_by(id=id).delete():
        db.session.commit()
        flash ('Review has been deleted', 'success')
        return redirect(url_for('main.reviews'))
    return redirect(url_for('main.reviews'))  

scrum_template/app/rooms/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from app.rooms.forms import AddRoomForm, EditRoomForm
from app.models import Room
from app.funcs import save_picture
from app import db
from flask_login import current_user, login_user, logout_user, login_required

rooms = Blueprint('rooms', __name__)

@rooms.route('/all_rooms')
def all_rooms():
    return 'All rooms page'

@rooms.route('/new_room', methods=['GET', 'POST'])
@login_required
def new_room():
    form = AddRoomForm()
    if form.validate_on_submit():
        image_file = 'default.jpg'
        if form.image.data:
            image_file = save_picture(form.image.data)
  
        room = Room(
            title=form.title.data,
            description=form.description.data,
            image=image_file,
            price=form.price.data,
        )
        db.session.add(room)
        db.session.flush()
        new_id = room.id
        db.session.commit()
        flash('Room was added successfully', 'success')
        return redirect(url_for('rooms.room', id=new_id))
    return render_template('rooms/new_room.html', title='Add room', form=form)

@rooms.route('/room/<id>', methods=['GET', 'POST'])
def room(id):
    room = Room.query.get(id)
    return render_template('rooms/room.html', title=room.title.title(), room=room)

@rooms.route('/room/edit/<id>', methods=['GET', 'POST'])
@login_required
def edit_room(id):
    room = Room.query.get(id)
    form = EditRoomForm(obj=room)
    if request.method == 'GET':
        form.populate_obj(room)
    elif request.method == 'POST':
        if form.update.data and form.validate_on_submit():
            room.title = form.title.data
            room.description = form.description.data
            if form.image.data:
                room.image = save_picture(form.image.data)
            room.price = form.price.data
            db.session.commit()
            flash ('Update was successful', 'success')
            return redirect(url_for('rooms.room', id=id))
        if form.cancel.data:
            return redirect(url_for('rooms.room', id=id))
    return render_template('rooms/edit_room.html', title='Edit room', form=form)

@rooms.route('/room/<id>/delete', methods=['GET', 'POST'])
@login_required
def delete_room(id):
    if Room.query.filter_by(id=id).delete():
        db.session.commit()
        flash ('Room has been deleted', 'success')
        return redirect(url_for('main.index'))
    return redirect(url_for('rooms.room', id=id)) 

@rooms.route('/search', methods=['GET', 'POST'])
def search():
    rooms = None
    target_string = request.form['search']

    rooms = Room.query.filter(Room.title.contains(target_string)).all()

    if target_string == '':
        search_msg = f'No matching records found - displaying all {len(rooms)} rooms'
        color = 'danger'
    else:
        search_msg = f'{len(rooms)} rooms found'
        color = 'success'
    return render_template('rooms/search.html', 
        title='Search result', rooms=rooms, 
        search_msg=search_msg, color=color
    )

scrum_template/app/templates/_enquiries.html
<table class="table">
    <tbody>
        <tr>
            <th>Submission Date</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Telephone Number</th>
            <th>Description</th>
        </tr>
        {% for enquiry in enquiries %}
        <tr>
            <td>{{ enquiry.created_at }}</td>
            <td>{{ enquiry.first_name }}</td>
            <td>{{ enquiry.last_name }}</td>
            <td>{{ enquiry.email }}</td>
            <td>{{ enquiry.telno }}</td>
            <td>{{ enquiry.description }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

scrum_template/app/templates/base.html
{% extends "bootstrap/base.html" %} {% block title %} {{ title }} | Weddings {% endblock %} {% block styles %} {{ super() }}
<link href="{{url_for('static', filename='css/styles.css')}}" rel="stylesheet"> {% endblock %} {% block navbar %}
<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
            <a href="{{ url_for('main.index') }}" class="navbar-brand">Stately Home |</a>
        </div>
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <ul class="nav navbar-nav">
                <li>
                    <!--Car Hire, Catering, Photography, Music, Flower Decorations-->
                    <a href="{{ url_for('main.services') }}">Services</a>

                </li>
                <li>
                    <a href="{{ url_for('main.packagedeals') }}">Package Deals</a>
                </li>
                <li>
                    <a href="{{ url_for('main.reviews') }}">Reviews</a>
                </li>
                <li>
                    <a href="{{ url_for('main.contact') }}">Contact Us</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <form class="navbar-form navbar-left" method='POST' action="{{ url_for('rooms.search') }}">
                        <div class="form-group">
                            <input class="form-control mr-sm-2" placeholder="Search" aria-label="Search" type="text" name="search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </div>
                    </form>
                </li>
                {% if current_user.is_authenticated and current_user.admin %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"> </span> {{ current_user.username }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('rooms.new_room') }}">Add a room</a></li>
                        <li><a href="{{ url_for('bookings.wedbookings') }}">View wedding bookings</a></li>
                        <li><a href="{{ url_for('bookings.tourbookings') }}">View tour bookings</a></li>
                        <li><a href="{{ url_for('main.enquiries') }}">View enquiries</a></li>
                        <li><a href="{{ url_for('auth.userinfo') }}">User Information</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    </ul>
                </li>
                {% elif current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"> </span> {{ current_user.username }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('bookings.wedbooking') }}">Make a Wedding Booking</a></li>
                        <li><a href="{{ url_for('bookings.tourbooking') }}">Make a Tour Booking</a></li>
                        <li><a href="{{ url_for('auth.userinfo') }}">User Information</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

{% endblock %} {% block content %}
<div class="container-full-bg">
    {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %}
    <div class="alert alert-{{ category }} text-center">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </a>
        {{ message }}
    </div>
    {% endfor %} {% endif %} {% endwith %}
</div>


{# application content needs to be provided in the app_content block #} {% block app_content %}{% endblock %}



<div class="container">
    <footer class="footer navbar-fixed-bottom">
        <div class="container">
            <p class="text-muted text-center">
                &copy;
                <script>
                    document.write(
                        new Date().getFullYear())
                </script>, Stately Home | Weddings
            </p>
        </div>
    </footer>
</div>
{% endblock %} {% block scripts %} {{ super() }} {{ moment.include_moment() }}
<script src="{{ url_for('static', filename='js/raty/lib/jquery.raty.js') }}"></script>
<script src="{{ url_for('static', filename='js/main.js') }}"></script>
<script type="text/javascript">
    window.setTimeout(function() {
        $(".alert").fadeTo(500, 0).slideUp(500, function() {
            $(this).remove();
        });
    }, 3000);

    $(document).ready(function() {
        $('#star').raty({
            path: '/static/js/raty/lib/images',
            half: true,
            number: 5,
            score: $('#result').val(),
            starType: 'img',
            targetKeep: true,
            click: function(score, event) {
                $('#result').val(score);
            }
        });

        $('.avg-rating').raty({
            path: '/static/js/raty/lib/images',
            readOnly: true,
            score: function() {
                return $(this).attr('data-score');
            }
        });

        $('.star-rating').raty({
            path: '/static/js/raty/lib/images',
            readOnly: true,
            score: function() {
                return $(this).attr('data-score');
            }
        });

        $('[data-toggle="tooltip"]').tooltip();
    });
</script>
{% endblock %}

scrum_template/app/templates/contact.html
{% extends "base.html" %} {% import 'bootstrap/wtf.html' as wtf %} {% block app_content %}
<br><br>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Contact us - submit an enquiry!</h3>
            </div>
            <div class="panel-body">
                {{ wtf.quick_form(form, button_map={'submit':'success'}, extra_classes="text-muted") }}
            </div>
        </div>
    </div>
</div>

{% endblock %}

scrum_template/app/templates/enquiries.html
{% extends "base.html" %} {% block app_content %}
<div class="container">
    <div class="col-md-9 col-md-offset-1">
        <div class="row ">
            <h3 class="text-muted">Displaying <span class="text-{{color}}">{{ msg }}</span></h3>
            <hr> {% include '_enquiries.html' %}
        </div>
    </div>
</div>
{% endblock %}

scrum_template/app/templates/index.html
{% extends "base.html" %} {% block app_content %}
<div class="container-full-bg">
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Welcome!</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            <p class="lead">
                <a class="btn btn-primary btn-md" href="#" role="button">Learn more</a>
            </p>

        </div>
    </div>
</div>

{% endblock %}

scrum_template/app/templates/packagedeals.html
{% extends "base.html" %} {% block app_content %}

<div class="pricing-table">
    <div class="container">
        <div class="block-heading">
            <h2>Package Deals</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in, mattis vitae leo.</p>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-5 col-lg-4">
                <div class="item">
                    <div class="heading">
                        <h3>STANDARD</h3>
                    </div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                    <div class="features">
                        <h4><span class="glyphicon glyphicon-ok-circle" style="color: #99C07A;"></span> <span class="feature">Wedding Hall</span></h4>
                        <h4><span class="glyphicon glyphicon-ok-circle" style="color: #99C07A;"></span> <span class="feature">Catering</span></h4>
                        <h4 class="text-muted"><span class="glyphicon glyphicon-remove-circle"></span> <span class="feature">Flower Decorations</span></h4>
                        <h4 class="text-muted"><span class="glyphicon glyphicon-remove-circle"></span> <span class="feature">Visual & Audio System</span></h4>
                        <h4 class="text-muted"><span class="glyphicon glyphicon-remove-circle"></span> <span class="feature">Photography</span></h4>
                        <h4 class="text-muted"><span class="glyphicon glyphicon-remove-circle"></span> <span class="feature">Car Hire</span></h4>
                    </div>
                    <div class="price">
                        <h4>£200</h4>
                    </div>
                    <!-- <button class="btn btn-block btn-outline-primary" type="submit">BUY NOW</button> -->
                </div>
            </div>
            <div class="col-md-5 col-lg-4">
                <div class="item">
                    <div class="ribbon">Best Value</div>
                    <div class="heading">
                        <h3>ESSENTIALS</h3>
                    </div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                    <div class="features">
                        <h4><span class="glyphicon glyphicon-ok-circle" style="color: #99C07A;"></span> <span class="feature">Wedding Hall</span></h4>
                        <h4><span class="glyphicon glyphicon-ok-circle" style="color: #99C07A;"></span> <span class="feature">Catering</span></h4>
                        <h4><span class="glyphicon glyphicon-ok-circle" style="color: #99C07A;"></span> <span class="feature">Flower Decorations</span></h4>
                        <h4><span class="glyphicon glyphicon-ok-circle" style="color: #99C07A;"></span> <span class="feature">Visual & Audio System</span></h4>
                        <h4 class="text-muted"><span class="glyphicon glyphicon-remove-circle"></span> <span class="feature">Photography</span></h4>
                        <h4 class="text-muted"><span class="glyphicon glyphicon-remove-circle"></span> <span class="feature">Car Hire</span></h4>
                    </div>
                    <div class="price">
                        <h4>£500</h4>
                    </div>
                    <!-- <button class="btn btn-block btn-primary" type="submit">BUY NOW</button> -->
                </div>
            </div>
            <div class="col-md-5 col-lg-4">
                <div class="item">
                    <div class="heading">
                        <h3>PREMIUM</h3>
                    </div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                    <div class="features">
                        <h4><span class="glyphicon glyphicon-ok-circle" style="color: #99C07A;"></span> <span class="feature">Wedding Hall</span></h4>
                        <h4><span class="glyphicon glyphicon-ok-circle" style="color: #99C07A;"></span> <span class="feature">Catering</span></h4>
                        <h4><span class="glyphicon glyphicon-ok-circle" style="color: #99C07A;"></span> <span class="feature">Flower Decorations</span></h4>
                        <h4><span class="glyphicon glyphicon-ok-circle" style="color: #99C07A;"></span> <span class="feature">Visual & Audio System</span></h4>
                        <h4><span class="glyphicon glyphicon-ok-circle" style="color: #99C07A;"></span> <span class="feature">Photography</span></h4>
                        <h4><span class="glyphicon glyphicon-ok-circle" style="color: #99C07A;"></span> <span class="feature">Car Hire</span></h4>
                    </div>
                    <div class="price">
                        <h4>£1000</h4>
                    </div>
                    <!-- <button class="btn btn-block btn-outline-primary" type="submit">BUY NOW</button> -->
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

scrum_template/app/templates/services.html
{% extends "base.html" %} {% block app_content %}

<div class="container">

    <h1 class="my-4">Services</h1>
    <br>

    <div class="row">
        <div class="col-md-7">
            <img class="img-fluid rounded mb-3 mb-md-0" src="https://imgur.com/bt33fx2.png" alt="">
        </div>
        <div class="col-md-5">
            <h3>Catering</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-md-7">
            <img class="img-fluid rounded mb-3 mb-md-0" src="https://imgur.com/quZhIwy.png" alt="">
        </div>
        <div class="col-md-5">
            <h3>Photography</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, odit velit cumque vero doloremque repellendus distinctio maiores rem expedita a nam vitae modi quidem similique ducimus! Velit, esse totam tempore.</p>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-md-7">
            <img class="img-fluid rounded mb-3 mb-md-0" src="https://imgur.com/sXegUaB.png" alt="">
        </div>
        <div class="col-md-5">
            <h3>Car Hire</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, temporibus, dolores, at, praesentium ut unde repudiandae voluptatum sit ab debitis suscipit fugiat natus velit excepturi amet commodi deleniti alias possimus!</p>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-md-7">
            <img class="img-fluid rounded mb-3 mb-md-0" src="https://imgur.com/6ukrCVw.png" alt="">
        </div>
        <div class="col-md-5">
            <h3>Visual & Audio Systems</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, quidem, consectetur, officia rem officiis illum aliquam perspiciatis aspernatur quod modi hic nemo qui soluta aut eius fugit quam in suscipit.</p>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-md-7">
            <img class="img-fluid rounded mb-3 mb-md-0" src="https://imgur.com/MAZw7S1.png" alt="">
        </div>
        <div class="col-md-5">
            <h3>Flower Decorations</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p>
        </div>
    </div>
    <hr><br>

</div>

{% endblock %}